/**
 * Verbs Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.api;

import io.swagger.model.Verb;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Verbs Service
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API tests for DefaultApi 
 */
public class DefaultApiTest {


    private DefaultApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("http://localhost:8080/v1", DefaultApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    /**
     * Add a new Verb
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addVerbTest() {
        Verb body = null;
        //api.addVerb(body);
        
        // TODO: test validations
        
        
    }
    /**
     * Delete verb by name
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteVerbTest() {
        String name = null;
        //api.deleteVerb(name);
        
        // TODO: test validations
        
        
    }
    /**
     * Get verb by name
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVerbByNameTest() {
        String name = null;
        //Verb response = api.getVerbByName(name);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Get verbs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVerbsTest() {
        //List<Verb> response = api.getVerbs();
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Update verb by name
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateVerbTest() {
        Verb body = null;
        String name = null;
        //api.updateVerb(body, name);
        
        // TODO: test validations
        
        
    }
}
