package de.mneifercons.examples.service.api;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.model.wadl.Description;
import org.apache.cxf.jaxrs.model.wadl.DocTarget;

import de.mneifercons.examples.service.model.Verb;

import org.apache.cxf.jaxrs.ext.multipart.*;

/**
 * Verbs Service
 *
 * <p>
 * No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 */
public class DefaultApiServiceImpl implements DefaultApi {
    /**
     * Add a new Verb
     *
     */
    public void addVerb(Verb body) {
        // TODO: Implement...

    }

    /**
     * Delete verb by name
     *
     */
    public void deleteVerb(String name) {
        // TODO: Implement...

    }

    /**
     * Get verb by name
     *
     */
    public Verb getVerbByName(String name) {
        // TODO: Implement...

        return null;
    }

    /**
     * Get verbs
     *
     */
    public List<Verb> getVerbs() {
        // TODO: Implement...

        return null;
    }

    /**
     * Update verb by name
     *
     */
    public void updateVerb(Verb body, String name) {
        // TODO: Implement...

    }

}
