package eu.mneifercons.examples.service.api;

import java.util.List;

import eu.mneifercons.examples.service.model.Verb;

/**
 * Verbs Service
 *
 * <p>
 * No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 */
public class DefaultApiServiceImpl implements DefaultApi {
    /**
     * Add a new Verb
     *
     */
    public void addVerb(Verb body) {
        // TODO: Implement...

    }

    /**
     * Delete verb by name
     *
     */
    public void deleteVerb(String name) {
        // TODO: Implement...

    }

    /**
     * Get verb by name
     *
     */
    public Verb getVerbByName(String name) {
        // TODO: Implement...

        return null;
    }

    /**
     * Get verbs
     *
     */
    public List<Verb> getVerbs() {
        // TODO: Implement...

        return null;
    }

    /**
     * Update verb by name
     *
     */
    public void updateVerb(Verb body, String name) {
        // TODO: Implement...

    }

}
